version: '3'

services:
  db:
    container_name: pizzaria-database
    hostname: pizaria_database
    image: postgres:15.1
    restart: unless-stopped
    networks:
      - pizaria_network
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=pizzaria_database
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/pizzaria/data:/var/lib/postgresql/data:rw

networks:
  pizaria_network: